MVICore/src/main/java/com/badoo/mvicore/binder/internal/ScopedBinding.kt
Fix for proper handling of the scope
=> fixed scope binding

MVICore/src/main/java/com/badoo/mvicore/element/TimeCapsuleWrapper.kt
Add ability to wrap TimeCapsule and provide suffix for keys
=> Add TimeCapsuleWrapper

README.md
New badges for version and license
=> Update Readme.md: add badges

build.gradle, mvicore-android/build.gradle, mvicore-android/src/androidTest/java/com/badoo/mvicore/android/AndroidTimeCapsuleTest.kt, mvicore-android/src/main/java/com/badoo/mvicore/android/AndroidTimeCapsule.kt
=> Use kotlin forEach instead of java

mvicore/src/main/java/com/badoo/mvicore/binder/Binder.kt, mvicore/src/test/java/com/badoo/mvicore/lifecycle/LifecycleTest.kt
=> Subscribe connections on first BEGIN event only

build.gradle, gradle/wrapper/gradle-wrapper.properties, mvicore-android/build.gradle, mvicore-debugdrawer/build.gradle, mvicore-demo/mvicore-demo-app/build.gradle, mvicore-demo/mvicore-demo-catapi/build.gradle, mvicore-demo/mvicore-demo-feature1/build.gradle, mvicore-demo/mvicore-demo-feature2/build.gradle, mvicore-diff/build.gradle, mvicore/build.gradle
Updated Kotlin and RxJava versions.
=> Update dependencies for 1.2.0

README.md, documentation/index.md
I was checking out the new ModelWatcher tool and it took me longer than I'd like to admit to realize it was a separate artifact so I figured I'd add it the docs to make it more clear.
=> Add diff artifact to docs

documentation/extras/modelwatcher.md
=> Use right name for diff strategy parameter in docs

mvicore-android/src/main/java/com/badoo/mvicore/android/AndroidBindings.kt, mvicore/src/main/java/com/badoo/mvicore/binder/Binder.kt, mvicore/src/main/java/com/badoo/mvicore/binder/lifecycle/Lifecycle.kt, mvicore/src/main/java/com/badoo/mvicore/connector/Connector.kt, mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/ConsumerMiddleware.kt, mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/base/Middleware.kt, mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/MiddlewareConfiguration.kt, mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/Middlewares.kt, mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/WrappingCondition.kt, mvicore/src/main/java/com/badoo/mvicore/middleware/Middleware.kt
It doesn't make everything to compile successfully, but helps identifying some new imports with `ReplaceWith` clauses.
=> Add typealiases to give guidance where classes are moved

build.gradle, mvicore-android/build.gradle, mvicore-debugdrawer/build.gradle
Restored deleted by mistake publishing for mvicore-android and mvicore-debugdrawer, fixed #137
=> Restored publishing for mvicore-android and mvicore-debugdrawer

mvicore/src/test/java/com/badoo/mvicore/bootstrapper/BootstrapperTest.kt
=> Bootstrapper tests

.github/workflows/build.yml, build.gradle, mvicore-debugdrawer/build.gradle, mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/main/HelpDialogFragment.kt, mvicore-demo/mvicore-demo-catapi/build.gradle
=> GitHub Actions setup

.github/pull_request_template.md, documentation/whatsnew.md
There is quite a lot of changes missing from whatsnew.md
=> Retrospectively updated missing changes to whatsnew.md

.github/workflows/documentation.yml
Fixed the branch that the documentation triggers on.
=> Changed documentation branch to master

documentation/whatsnew.md, mvicore/src/main/java/com/badoo/mvicore/feature/BaseFeature.kt, mvicore/src/test/java/com/badoo/mvicore/feature/BaseFeaturePostProcessorTest.kt
=> [#167] Reverted BaseFeature PostProcessor recursion behaviour change

binder/build.gradle, build.gradle, gradle/libs.versions.toml, mvicore-android/build.gradle, mvicore-debugdrawer/build.gradle, mvicore-demo/mvicore-demo-app/build.gradle, mvicore-demo/mvicore-demo-catapi/build.gradle, mvicore-demo/mvicore-demo-feature1/build.gradle, mvicore-demo/mvicore-demo-feature2/build.gradle, mvicore-diff/build.gradle, mvicore-plugin/common/build.gradle, mvicore-plugin/idea/build.gradle, mvicore-plugin/middleware/build.gradle, mvicore/build.gradle, plugin/publish-plugin/build.gradle.kts, plugin/publish-plugin/settings.gradle.kts, settings.gradle
Migrate to version catalog (depends on #162)
=> Use version catalog

CHANGELOG.md, build.gradle, gradle/libs.versions.toml
Do not merge until Appyx is updated to 1.7.0
=> Update Kotlin to 1.7.10

CHANGELOG.md, gradle/libs.versions.toml
Updated RxJava and RxKotlin to latest versions
=> Updated RxJava and RxKotlin to latest versions

CHANGELOG.md, binder/build.gradle, gradle/libs.versions.toml, mvicore-android/build.gradle, mvicore-android/lint-baseline.xml, mvicore-debugdrawer/build.gradle, mvicore-debugdrawer/lint-baseline.xml, mvicore-demo/mvicore-demo-app/build.gradle, mvicore-demo/mvicore-demo-app/lint-baseline.xml, mvicore-demo/mvicore-demo-catapi/build.gradle, mvicore-demo/mvicore-demo-catapi/lint-baseline.xml, mvicore-demo/mvicore-demo-feature1/build.gradle, mvicore-demo/mvicore-demo-feature1/lint-baseline.xml, mvicore-demo/mvicore-demo-feature2/build.gradle, mvicore-demo/mvicore-demo-feature2/lint-baseline.xml, mvicore-diff/build.gradle, mvicore-plugin/common/build.gradle, mvicore-plugin/idea/build.gradle, mvicore-plugin/middleware/build.gradle, mvicore/build.gradle
Updated AndroidX libs and target sdk to 33
=> Updated AndroidX libs and target sdk to 33

.github/workflows/build.yml
Copied workflow from Appyx to ensure instrumentation tests on CI are more stable.
=> Fixed stability of workflow instrumentation tests

CHANGELOG.md
Updated changelog for version 1.4.0
=> Updated changelog for version 1.4.0

gradle/libs.versions.toml, mvicore-demo/mvicore-demo-app/lint-baseline.xml, mvicore-demo/mvicore-demo-app/lint.xml, mvicore-demo/mvicore-demo-app/src/main/AndroidManifest.xml, mvicore-demo/mvicore-demo-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, mvicore-demo/mvicore-demo-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
=> Updated AGP to 7.4.1

gradle/libs.versions.toml, mvicore/src/test/java/com/badoo/mvicore/newspublishing/NewsPublishingTest.kt
=> Updated detekt to 1.22.0

gradle/libs.versions.toml
Updated internal libraries to latest versions
=> Updated internal libraries to latest versions

.github/workflows/build.yml, binder/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml, mvicore-android/build.gradle.kts, mvicore-debugdrawer/build.gradle.kts, mvicore-demo/mvicore-demo-app/build.gradle.kts, mvicore-demo/mvicore-demo-catapi/build.gradle.kts, mvicore-demo/mvicore-demo-feature1/build.gradle.kts, mvicore-demo/mvicore-demo-feature2/build.gradle.kts, mvicore-diff/build.gradle.kts, mvicore-diff/src/test/java/com/badoo/mvicore/ModelWatcherTest.kt, mvicore-plugin/common/build.gradle.kts, mvicore-plugin/idea/build.gradle.kts, mvicore-plugin/middleware/build.gradle.kts, mvicore/build.gradle.kts
Introduced dependency analysis plugin and fixed issues
- [x ] I have updated documentation if required.
=> Introduced dependency analysis plugin and fixed issues

mvicore-android/build.gradle.kts, mvicore-android/src/main/AndroidManifest.xml, mvicore-debugdrawer/build.gradle.kts, mvicore-debugdrawer/src/main/AndroidManifest.xml, mvicore-demo/mvicore-demo-app/build.gradle.kts, mvicore-demo/mvicore-demo-app/src/main/AndroidManifest.xml, mvicore-demo/mvicore-demo-catapi/build.gradle.kts, mvicore-demo/mvicore-demo-catapi/src/main/AndroidManifest.xml, mvicore-demo/mvicore-demo-feature1/build.gradle.kts, mvicore-demo/mvicore-demo-feature1/src/main/AndroidManifest.xml, mvicore-demo/mvicore-demo-feature2/build.gradle.kts, mvicore-demo/mvicore-demo-feature2/src/main/AndroidManifest.xml
Migrated to gradle namespace instead of manifest package
=> Migrated to gradle namespace instead of manifest package

.github/workflows/build.yml, binder/build.gradle.kts, build.gradle.kts, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, jitpack.yml, mvicore-android/lint-baseline.xml, mvicore-debugdrawer/lint-baseline.xml, mvicore-demo/mvicore-demo-app/build.gradle.kts, mvicore-demo/mvicore-demo-app/lint-baseline.xml, mvicore-demo/mvicore-demo-catapi/lint-baseline.xml, mvicore-demo/mvicore-demo-feature1/lint-baseline.xml, mvicore-demo/mvicore-demo-feature2/lint-baseline.xml, mvicore-diff/build.gradle.kts, mvicore-plugin/common/build.gradle.kts, mvicore-plugin/idea/build.gradle.kts, mvicore-plugin/middleware/build.gradle.kts, mvicore-plugin/templates/build.gradle.kts, mvicore/build.gradle.kts, plugins/publish-plugin/build.gradle.kts, plugins/verification-plugin/build.gradle.kts, settings.gradle.kts
Updating AGP to the latest stable version
=> Updated AGP to 8.0.2

CHANGELOG.md, gradle/libs.versions.toml, mvicore-android/build.gradle.kts, mvicore-android/src/test/java/com/badoo/mvicore/android/lifecycle/TestLifecycleOwner.kt, mvicore-debugdrawer/build.gradle.kts, mvicore-demo/mvicore-demo-app/build.gradle.kts, mvicore-demo/mvicore-demo-catapi/build.gradle.kts, mvicore-demo/mvicore-demo-feature1/build.gradle.kts, mvicore-demo/mvicore-demo-feature2/build.gradle.kts
Align MVICore dependencies with the current Appyx 2.0 versions.
=> Aligned dependencies wth Appyx
