mvicore/src/main/java/com/badoo/mvicore/element/Actor.kt
mvicore/src/main/java/com/badoo/mvicore/element/NewsPublisher.kt
mvicore/src/main/java/com/badoo/mvicore/element/PostProcessor.kt
mvicore/src/main/java/com/badoo/mvicore/element/Reducer.kt
mvicore/src/main/java/com/badoo/mvicore/element/WishToAction.kt

If you extend these interfaces, and use AS to generate default implementation it will generate something like:
```
override fun invoke(p1: Action, p2: State): Observable<Effect>
```
This PR improves readability of this a tiny bit, producing:
```
override fun invoke(action: Action, state: State): Observable<Effect>
```

Add named params to typealias elements

---

mvicore-android/src/main/java/com/badoo/mvicore/android/AndroidBindings.kt
mvicore/src/main/java/com/badoo/mvicore/binder/Binder.kt
mvicore/src/main/java/com/badoo/mvicore/binder/Connection.kt
mvicore/src/main/java/com/badoo/mvicore/binder/lifecycle/Lifecycle.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/Consumer.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/ConsumerMiddleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/LoggingMiddleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/PlaybackMiddleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/base/Middleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/base/StandaloneMiddleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/ConsumerMiddlewareFactory.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/MiddlewareConfiguration.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/WrappingCondition.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/playback/MemoryRecordStore.kt
mvicore/src/main/java/com/badoo/mvicore/feature/BaseFeature.kt

The `Connection` class we have right now is somehow limited for external observer (any middleware).
If you apply transformer, the only source the middleware will receive is `ObservableFlatMap` which is far from ideal.
This pull request tries to fix this issue, updating type signature to `Connection<Out, In>`, adding parameters for source and transformer and updating built-in middlewares to work with current implementation.
This PR does break backward compatibility for `Connection` usages, but I could not find any in our codebase, so I conclude it is not explicitly broadly used.

Add source parameter to the connection

---

documentation/extras/modelwatcher.md
mvicore-diff/build.gradle
mvicore-diff/src/main/java/com/badoo/mvicore/ModelWatcher.kt
mvicore-diff/src/test/java/com/badoo/mvicore/ModelWatcherTest.kt

Add some dsl inside the ModelWatcher.Builder, allowing for syntax like:
```kotlin
val watcher = modelWatcher {
ViewModel::buttonText {
button.text = it
}
}
```

Add syntactic sugar for watchers

---

documentation/binder/binder-advanced.md
mvicore/src/main/java/com/badoo/mvicore/binder/Binder.kt
mvicore/src/main/java/com/badoo/mvicore/binder/Connection.kt
mvicore/src/main/java/com/badoo/mvicore/connector/Connector.kt
mvicore/src/main/java/com/badoo/mvicore/connector/NotNullConnector.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/Consumer.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/base/Middleware.kt
mvicore/src/main/java/com/badoo/mvicore/consumer/middlewareconfig/MiddlewareConfiguration.kt
mvicore/src/test/java/com/badoo/mvicore/binder/BinderTest.kt

We used to allow covariance between endpoint and source before connection update.
This PR returns that, effectively allowing you to use more generic type on the consumer.
```
private val source: Observable<Int>
private val consumer: Consumer<Any>
binder.bind(source to consumer) // Now compiles
```

Allow covariant endpoints

---

mvicore/src/main/java/com/badoo/mvicore/binder/Connection.kt
mvicore/src/test/java/com/badoo/mvicore/binder/BinderTest.kt

While doing #86, I forgot about types in our dsl methods, so here they are fixed as well.

Fix variance for types in dsl methods

---

documentation/extras/modelwatcher.md
mvicore-diff/src/main/java/com/badoo/mvicore/ModelWatcher.kt
mvicore-diff/src/test/java/com/badoo/mvicore/ModelWatcherTest.kt

Allows for better syntax when observing two fields.
```
// Base syntax
val diff = { old, new -> old.list != new.list || old.int != new.int }
watch({ it }, diff) { }
// DSL
(Model::list or Model::int) { }
```

Add dsl to combine selectors on fields for ModelWatcher

---

mvicore-debugdrawer/build.gradle

Seems like I have accidentally added the debug drawer base artifact for debug only. ¯\\_(ツ)_/¯

Fix 1.2.0 debug drawer build

---

documentation/middlewares/loggingmiddleware.md

[LoggingMiddleware file link](https://github.com/badoo/MVICore/mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/LoggingMiddleware.kt) from the [documentation](https://badoo.github.io/MVICore/middlewares/loggingmiddleware/) was leading nowhere.
Replace it with [a working link](https://github.com/badoo/MVICore/blob/master/mvicore/src/main/java/com/badoo/mvicore/consumer/middleware/LoggingMiddleware.kt).

Fix broken link in logging middleware documentation

---

binder/build.gradle
binder/src/test/java/com/badoo/binder/LifecycleTest.kt
build.gradle
mvicore/build.gradle
mvicore/src/test/java/com/badoo/mvicore/newspublishing/NewsPublishingTest.kt

- Updated mockito-kotlin library to `org.mockito.kotlin:mockito-kotlin:3.2.0`
- Fixed imports in `NewsPublishingTest.kt` and `LifecycleTest.kt`

Mockito-kotlin dependency updated

---

mvicore-demo/mvicore-demo-feature2/src/main/java/com/badoo/feature2/Feature2.kt
mvicore/src/main/java/com/badoo/mvicore/element/Bootstrapper.kt

Now, when I want to do something like this:
```kotlin
private class BootstrapperImpl(
private val dataSource: DataSource,
) : Bootstrapper<Action> {
override fun invoke(): Observable<Action> =
dataSource
.observe()
.map { Action.NameChanged(it.name) }
.distinctUntilChanged()
}
```
I need to explicitly specify `.map` generic type:
```kotlin
.map<Action> { Action.NameChanged(it.name) }
.distinctUntilChanged()
```
So, generic `Action` in `Bootstrapper` should be covariant (like `Actor`) to be more flexible in such cases

Fixed Bootstrapper variance

---

mvicore/src/main/java/com/badoo/mvicore/feature/ActorReducerFeature.kt
mvicore/src/main/java/com/badoo/mvicore/feature/BaseFeature.kt
mvicore/src/main/java/com/badoo/mvicore/feature/FeatureSchedulers.kt
mvicore/src/main/java/com/badoo/mvicore/feature/MemoFeature.kt
mvicore/src/main/java/com/badoo/mvicore/feature/ReducerFeature.kt
mvicore/src/test/java/com/badoo/mvicore/feature/AsyncBaseFeatureTest.kt

Made a few changes to the recent async actor change introduced last week.
- Renamed the `BaseFeature.Schedulers` class to `FeatureSchedulers`
- This caused a compilation issue with existing 'legacy' features that pass in a scheduler as there is a name conflict between the imports.
- Added the new schedulers to the `BaseFeature` subtypes.

Async actor improvements

---

binder/build.gradle
mvicore-android/build.gradle
mvicore-debugdrawer/build.gradle
mvicore-demo/mvicore-demo-app/build.gradle
mvicore-demo/mvicore-demo-catapi/build.gradle
mvicore-demo/mvicore-demo-feature1/build.gradle
mvicore-demo/mvicore-demo-feature2/build.gradle
mvicore-diff/build.gradle
mvicore-plugin/common/build.gradle
mvicore-plugin/idea/build.gradle
mvicore-plugin/middleware/build.gradle
mvicore/build.gradle

Fixes a regression in the build (caught by github actions) where the running AndroidTests was failing due to an issue with desugaring:
> * What went wrong:
> Execution failed for task ':mvicore-demo:mvicore-demo-feature2:mergeExtDexDebugAndroidTest'.
> > Could not resolve all files for configuration ':mvicore-demo:mvicore-demo-feature2:debugAndroidTestRuntimeClasspath'.
>    > Failed to transform lifecycle-common-java8-2.2.0.jar (androidx.lifecycle:lifecycle-common-java8:2.2.0) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
>       > Execution failed for …

Changed to Java 8 compatibility to fix build

---

mvicore/src/main/java/com/badoo/mvicore/extension/SameThreadVerifier.kt
mvicore/src/main/java/com/badoo/mvicore/feature/BaseAsyncFeature.kt
mvicore/src/main/java/com/badoo/mvicore/feature/BaseFeature.kt
mvicore/src/test/java/com/badoo/mvicore/extension/SameThreadVerifierTest.kt

Improves the SameThreadVerifier error message, allowing a developer to easily see which feature the error occurred on, and what the thread names are.

Improved SameThreadVerifier error message

---

mkdocs.yml

The material logo was causing the documentation to not build. I have updated it to the correct path.

Fixed mkdocs logo

---

.github/workflows/build.yml
.gitignore
CHANGELOG.md
binder/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties
jitpack.yml
mvicore-android/build.gradle
mvicore-debugdrawer/build.gradle
mvicore-demo/mvicore-demo-app/build.gradle
mvicore-demo/mvicore-demo-app/src/main/AndroidManifest.xml
mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/lifecycle/LifecycleDemoActivity.kt
mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/login/LoginActivity.kt
mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/main/MainActivity.kt
mvicore-demo/mvicore-demo-catapi/build.gradle
mvicore-demo/mvicore-demo-feature1/build.gradle
mvicore-demo/mvicore-demo-feature2/build.gradle
mvicore-demo/mvicore-demo-feature2/src/main/java/com/badoo/feature2/Feature2.kt
mvicore-diff/build.gradle
mvicore-plugin/common/build.gradle
mvicore-plugin/idea/build.gradle
mvicore-plugin/middleware/build.gradle
mvicore-plugin/templates/build.gradle
mvicore/build.gradle
plugin/publish-plugin/build.gradle.kts
plugin/publish-plugin/settings.gradle.kts
plugin/publish-plugin/src/main/kotlin/AndroidMviCorePublishPlugin.kt
plugin/publish-plugin/src/main/kotlin/JavaMviCorePublishPlugin.kt
plugin/publish-plugin/src/main/kotlin/MviCorePublishPlugin.kt
settings.gradle

Update kotlin to 1.6.21

---

plugins/verification-plugin/src/main/kotlin/CollectSarifPlugin.kt
plugins/verification-plugin/src/main/kotlin/DetektPlugin.kt

SARIFs basePath property is properly supported by Detekt, we do not need this fix.

Use detekt.basePath instead of changing paths manually

---

detekt.yml
mvicore-android/src/test/java/com/badoo/mvicore/android/lifecycle/LifecycleExtensionsTest.kt
mvicore-android/src/test/java/com/badoo/mvicore/android/lifecycle/TestLifecycleOwner.kt

Added unit tests for binder lifecycle extensions (changelog changes are not needed)

Added tests for binder lifecycle extensions

---

CHANGELOG.md
binder/src/main/java/com/badoo/binder/Binder.kt
binder/src/main/java/com/badoo/binder/Connection.kt
documentation/binder/binder-advanced.md
mvicore-android/src/test/java/com/badoo/mvicore/android/lifecycle/LifecycleExtensionsTest.kt

Proposal for allowing developers to set observation scheduler for Binder and lifecycle extensions.

Introduced LifecycleExtensions overloads to set observation schedulers

---

binder/build.gradle
binder/src/test/java/com/badoo/binder/BinderTest.kt
binder/src/test/java/com/badoo/binder/LifecycleTest.kt
binder/src/test/java/com/badoo/binder/TestConsumer.kt
gradle/libs.versions.toml
mvicore-android/build.gradle
mvicore-android/src/test/java/com/badoo/mvicore/android/lifecycle/LifecycleExtensionsTest.kt
mvicore-debugdrawer/build.gradle
mvicore-diff/build.gradle
mvicore-diff/src/test/java/com/badoo/mvicore/HelperTest.kt
mvicore-diff/src/test/java/com/badoo/mvicore/ModelWatcherTest.kt
mvicore-diff/src/test/java/com/badoo/mvicore/SealedClassTest.kt
mvicore-plugin/idea/build.gradle
mvicore/build.gradle
mvicore/src/test/java/com/badoo/mvicore/TestHelper.kt
mvicore/src/test/java/com/badoo/mvicore/bootstrapper/BootstrapperTest.kt
mvicore/src/test/java/com/badoo/mvicore/extension/SameThreadVerifierTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/AsyncBaseFeatureTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/BaseFeaturePostProcessorTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/BaseFeatureWithSchedulerTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/BaseFeatureWithoutSchedulerTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/TrampolineFeatureSchedulerTest.kt
mvicore/src/test/java/com/badoo/mvicore/newspublishing/NewsPublishingTest.kt
mvicore/src/test/java/com/badoo/mvicore/utils/RxErrorRule.kt

JUnit updated to version 5 (5.9.2)
...

Add junit5 dependency

---

CHANGELOG.md
binder/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
mvicore-android/build.gradle.kts
mvicore-debugdrawer/build.gradle.kts
mvicore-demo/mvicore-demo-app/build.gradle.kts
mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/common/ObservableSourceActivity.kt
mvicore-demo/mvicore-demo-app/src/main/java/com/badoo/mvicoredemo/ui/main/event/UiEvent.kt
mvicore-demo/mvicore-demo-catapi/build.gradle.kts
mvicore-demo/mvicore-demo-feature1/build.gradle.kts
mvicore-demo/mvicore-demo-feature1/src/main/java/com/badoo/feature1/Feature1.kt
mvicore-demo/mvicore-demo-feature2/build.gradle.kts
mvicore-demo/mvicore-demo-feature2/src/main/java/com/badoo/feature2/Feature2.kt
mvicore-diff/build.gradle.kts
mvicore-diff/src/test/java/com/badoo/mvicore/util/SealedModel.kt
mvicore-plugin/common/build.gradle.kts
mvicore-plugin/common/src/main/java/com/badoo/mvicore/plugin/model/Event.kt
mvicore-plugin/idea/build.gradle.kts
mvicore-plugin/middleware/build.gradle.kts
mvicore/build.gradle.kts
mvicore/src/main/java/com/badoo/mvicore/extension/Rx.kt
mvicore/src/test/java/com/badoo/mvicore/TestHelper.kt
mvicore/src/test/java/com/badoo/mvicore/bootstrapper/BootstrapperTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/BaseFeaturePostProcessorTest.kt
mvicore/src/test/java/com/badoo/mvicore/feature/TrampolineFeatureSchedulerTest.kt
mvicore/src/test/java/com/badoo/mvicore/newspublishing/NewsPublishingTest.kt

Updated Kotlin to 1.9.23

---

.github/workflows/build.yml

See https://github.com/ReactiveCircus/android-emulator-runner/issues/386

Use older macos agent to support Android emulator
